name: demo-action

on:
  # push:
  #   branches: main

  issues:
    types: opened

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4
      - name: sample-run
        run: echo Hello World

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: ${{github.workspace}}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: my-artifact
          run: ls -R
